version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:42000
    volumes:
      - .:/code
      - ./code/backend/api/secret.py:/code/backend/api/secret.py
    ports:
      - "42000:42000"
    environment:
      - SECRET_KEY